"""Add destination IP and port to sessions

Revision ID: b519325d1f2b
Revises: 1a5b9822e49c
Create Date: 2025-12-29 21:11:45.297350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b519325d1f2b'
down_revision: Union[str, None] = '1a5b9822e49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smtp_sessions', sa.Column('dest_ip', sa.String(length=255), nullable=True))
    op.add_column('smtp_sessions', sa.Column('dest_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smtp_sessions', 'dest_port')
    op.drop_column('smtp_sessions', 'dest_ip')
    # ### end Alembic commands ###
