name: Docker Image CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov alembic
    - name: Run migrations and test with pytest
      run: |
        # Create migrations directory if it doesn't exist
        mkdir -p mailoney/migrations/versions
        
        # Set up alembic environment
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        
        # Create initial migration if it doesn't exist
        if [ ! -f mailoney/migrations/versions/1a5b9822e49c_initial_migration.py ]; then
          echo "Creating initial migration file"
          cp .github/initial_migration.py mailoney/migrations/versions/1a5b9822e49c_initial_migration.py
        fi
        
        # Run tests with verbose output and debugging
        PYTHONPATH=$(pwd) pytest -vv --log-cli-level=DEBUG

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/mailoney
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=sha,format=short
          latest
          
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
